### ISSUE TITLE
Message: align left icon and the first line of text

### ISSUE THREAD

**Issue by fernandoabolafio** [tiagoalvesdulce/pi-ui#117]
Currently, the icon is positioned a bit higher than the first line. They should be vertically-center aligned.

**Comment by amassarwi** [comment]
On it

**Comment by amassarwi** [comment]
On master locally - looks like was fixed ?

![image](https://user-images.githubusercontent.com/10324528/63638448-39dac000-c688-11e9-8684-e15055232c59.png)
