### ISSUE TITLE
Dropdown: align default trigger to dropdown's list vertically to the center

### ISSUE THREAD

**Issue by amassarwi** [tiagoalvesdulce/pi-ui#145]
**See user dropdown in spec:** https://xd.adobe.com/spec/4e7eb732-a445-46b0-4f7e-4152097a10c8-384f/screen/9e5fb199-8db1-44e1-b9ae-ffc1c9e505d4/Proposals-admin/ 

**Note**: we need to truncate the username when it overflows (can have up to 30 chars)

**Comment by amassarwi** [comment]
on it..

**Comment by fernandoabolafio** [comment]
closed on #147
