### ISSUE TITLE
Show tooltip with a feedback on CopyableText component

### ISSUE THREAD

**Issue by tiagoalvesdulce** [tiagoalvesdulce/pi-ui#83]

**Comment by camus-code** [comment]
Picking this one up!

**Comment by fernandoabolafio** [comment]
@camus-code I implemented a component on politeiagui which I think you can lift it up to pi-ui to use for this issue, check it out: https://github.com/decred/politeiagui/blob/master/src/componentsv2/CopyToClipboard/CopyToClipboard.jsx

**Comment by camus-code** [comment]
thanks for that @fernandoabolafio! I'll have a PR up in just a little bit.
