### ISSUE TITLE
Dropdown component

### ISSUE THREAD

**Issue by fernandoabolafio** [tiagoalvesdulce/pi-ui#89]
Examples:

https://xd.adobe.com/spec/25f9f648-8d13-446f-75aa-242b21116f87-53c8/screen/b3b495bf-1d90-4a5d-bdd7-6161c74b8b6d/Proposal-details-logged-in-user-Opened-menu-Mobile

https://xd.adobe.com/spec/25f9f648-8d13-446f-75aa-242b21116f87-53c8/screen/0bca9b12-ad49-4bf7-b380-72172aac9d1a/Public-proposal-logged-in-user-Mobile-2

**Comment by camus-code** [comment]
Picking this one up
