### ISSUE TITLE
Floating badge component

### ISSUE THREAD

**Issue by fernandoabolafio** [tiagoalvesdulce/pi-ui#90]
This component needs to expose an API for the consumer to select one of the following icons:

![Screen Shot 2019-07-16 at 15 16 50](https://user-images.githubusercontent.com/14864439/61297611-e0f05000-a7dc-11e9-8522-6604284f78e1.png)
![Screen Shot 2019-07-16 at 15 16 46](https://user-images.githubusercontent.com/14864439/61297616-e483d700-a7dc-11e9-82d6-db489b2e5a91.png)
![Screen Shot 2019-07-16 at 15 16 41](https://user-images.githubusercontent.com/14864439/61297620-e64d9a80-a7dc-11e9-9c78-948a9ffc29c4.png)
![Screen Shot 2019-07-16 at 15 16 36](https://user-images.githubusercontent.com/14864439/61297627-e8175e00-a7dc-11e9-95a4-b0d7facb9b7d.png)

Example in the specs:

https://xd.adobe.com/spec/25f9f648-8d13-446f-75aa-242b21116f87-53c8/screen/573ae56d-a921-4fd7-a684-71c65bc60089/Create-proposal-file-attached-invalid-mime-type

https://xd.adobe.com/spec/25f9f648-8d13-446f-75aa-242b21116f87-53c8/screen/ad844292-79f7-470d-807b-8eb38324e9ca/Notification-example-1

https://xd.adobe.com/spec/25f9f648-8d13-446f-75aa-242b21116f87-53c8/screen/05b86566-f6c6-442f-9dc5-189ffa4b1ac2/Notification-example-2

https://xd.adobe.com/spec/25f9f648-8d13-446f-75aa-242b21116f87-53c8/screen/86f7490b-41dc-4cd7-8afe-b051e88ee1a1/Notification-example-3

**Comment by camus-code** [comment]
Working on this one
